### ISSUE TITLE
Couldn't compile

### ISSUE THREAD

**Issue by cysin** [lpre/Fastcgi-Container#1]
> make[1]: Entering directory `/root/work/Fastcgi-Container/library'
> 
> /bin/sh ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../config  -I../include -I../config -I/usr/include/libxml2   -pthread -pthread -g -O2 -W -Wall -Wextra -fexceptions -frtti -ftemplate-depth-128 -std=c++0x -MT handler.lo -MD -MP -MF .deps/handler.Tpo -c -o handler.lo handler.cpp
> libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../config -I../include -I../config -I/usr/include/libxml2 -pthread -pthread -g -O2 -W -Wall -Wextra -fexceptions -frtti -ftemplate-depth-128 -std=c++0x -MT handler.lo -MD -MP -MF .deps/handler.Tpo -c handler.cpp  -fPIC -DPIC -o .libs/handler.o
> In file included from ../include/details/handler_context.h:23:0,
> 
>   from handler.cpp:22:
> 
> ../include/fastcgi3/handler.h:25:24: fatal error: core/any.hpp: No such file or directory
> 
>  #include "core/any.hpp"
>                         ^
> 
> compilation terminated.
> 
> make[1]: **\* [handler.lo] Error 1
> 
> make[1]: Leaving directory `/root/work/Fastcgi-Container/library'
> 
> make: **\* [all-recursive] Error 1

**Comment by cysin** [comment]
Sorry I just found out that should be 'MNMLSTC Core', but could you please write it in the doc about how to integrate 'MNMLSTC Core' with Fastcgi-Container?

**Comment by lpre** [comment]
Comment added to file README.md
